#!/bin/bash
set -e

# --- CONFIGURATION ---
# The branch you want to deploy (Defaults to master if not found)
BRANCH="master"
SITE="frappe-his.sumasoft.com"
DB_PASS="9W3Or04mztlJMGl7" # From previous context
REPO_URL="https://source.developers.google.com/p/sumatoolkitservice/r/frappe_codebase"
# ---------------------

echo "⚠️  WARNING: THIS WILL DELETE EVERYTHING IN /home/frappe/frappe-bench ⚠️"
echo "You have 5 seconds to cancel (Ctrl+C)..."
sleep 5

echo "--- 1. Stopping Services ---"
sudo service supervisor stop
sudo service nginx stop

echo "--- 2. Wiping Frappe Bench ---"
# Back up just in case
if [ -d "/home/frappe/frappe-bench" ]; then
    echo "Backing up existing bench to /home/frappe/frappe-bench.bak..."
    mv /home/frappe/frappe-bench /home/frappe/frappe-bench.bak.$(date +%s)
fi

echo "--- 3. Cloning Fresh Repo ($BRANCH) ---"
# Clone as frappe user
mkdir -p /home/frappe/frappe-bench
chown frappe:frappe /home/frappe/frappe-bench
cd /home/frappe

# Clone
sudo -u frappe git clone "$REPO_URL" frappe-bench
cd frappe-bench
sudo -u frappe git checkout "$BRANCH" || echo "Branch $BRANCH not found, staying on default."

echo "--- 4. Installing Dependencies ---"
# Install Bench
sudo -u frappe pip3 install frappe-bench

# Env
sudo -u frappe python3 -m venv env
sudo -u frappe ./env/bin/pip install -U pip wheel setuptools

# Apps requirements
sudo -u frappe ./env/bin/pip install -e apps/frappe
if [ -d "apps/erpnext" ]; then sudo -u frappe ./env/bin/pip install -e apps/erpnext; fi
if [ -d "apps/healthcare" ]; then sudo -u frappe ./env/bin/pip install -e apps/healthcare; fi

# Node deps
sudo -u frappe yarn install

echo "--- 5. production setup ---"
sudo -u frappe ./env/bin/bench setup requirements
sudo ./env/bin/bench setup production frappe --yes

echo "--- 6. Restoring Data ---"
# We need to recreate the site config first
# (Assuming common_site_config is generated by setup production)
# ...

echo "✅  Reinstall Complete. Now verify the site."
